### ISSUE TITLE
Option for notifications about bed and hotend warmups complete? Or through g-code?

### ISSUE THREAD

**Issue by KriLL3** [OctoPrint/OctoPrint-Growl#4]
My printer is in another room than my computer and my heated bed can take a while to warm up, but I like to monitor the first few layers in person, an option to have the plugin send a growl notification when M190 (bed) and M109 (hotend) complete and/or add support for sending a message via g-code (so I can put in growl messages myself after the printer heats up) would be very useful and appreciated.

**Comment by foosel** [comment]
I'm closing this as I have no time to maintain this and my call for adoption of this plugin has also gone unanswered for close to two years now.
