### ISSUE TITLE
Registering With Growl Missing Tentacle Icon.

### ISSUE THREAD

**Issue by doughoyt** [OctoPrint/OctoPrint-Growl#6]
Not getting the cool tentacle icon when the plugin registers with Growl server.  In the _register_growl method, self.port is returning 5000, so the URL for kwargs["applicationIcon"] is referencing a location that will not return the image.  I'm not sure where that value is coming from (maybe sent by Octoprint during on_startup call?).

If I modify the line to not include a port (and let it default to 80 by Growl), I CAN get it to register with the correct icon.  However, that _seems_ to cause the test notification to timeout.  "Real" notifications (print start, print complete, etc.) appear to work, but the test notification times out and I can't explain it.

**Comment by foosel** [comment]
I'll try to find time to test this, I sadly - as usual - have my hands quite full with OctoPrint.

`self.port` indeed comes from the startup. Problem is that on OctoPi e.g. there's a haproxy in between and that port simply won't do. I'll try to figure out how to get around this (I have to admit, I don't actually use that plugin myself currently, so I didn't notice), but it might take a while.
